name: build when push
on: [push]

env:
  V8_VERSION: 9.4.147     # 8.4.380

defaults:
  run:
    shell: bash

jobs:
  build-linux-x64:
    # if: ${{ false }}  # disable
    name: linux-x64
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    strategy:
      fail-fast: false
      matrix:
        platform: [
          linux-x64-static-release,
          linux-x64-static-debug,
          linux-x64-shared-release,
          linux-x64-shared-debug
        ]
    env:
      PLATFORM: ${{ matrix.platform }}
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Platform env
        run: |
          uname -a
          echo "OS=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $1}')" >> $GITHUB_ENV
          echo "ARCH=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $2}')" >> $GITHUB_ENV
          echo "LIB_TYPE=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $3}')" >> $GITHUB_ENV
          echo "BUILD_TYPE=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $4}')" >> $GITHUB_ENV
      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y git python3 curl build-essential pkg-config ninja-build
          ln -s /usr/bin/python3 /usr/bin/python
          gcc --version
          ldd --version
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "PATH=${GITHUB_WORKSPACE}/depot_tools:${PATH}" >> $GITHUB_ENV
      - name: Patch depot_tools for python3.7
        run: |
          sed -i 's/@functools\.lru_cache\b/@functools.lru_cache(maxsize=128)/g' depot_tools/gclient_paths.py
      - name: Fetch v8 repository
        run: |
          gclient --version
          fetch v8
      - name: Sync v8 repository to target version
        run: |
          cd v8
          git checkout tags/${V8_VERSION}
          gclient sync -D
      - name: Compress headers, sources, sysroot
        if: env.LIB_TYPE == 'static' && env.BUILD_TYPE == 'release'
        run: |
          tar -czf v8-${V8_VERSION}-include.tar.gz v8/include
          tar -czf v8-${V8_VERSION}-src.tar.gz v8/src
          tar -czf v8-${V8_VERSION}-sysroot-${OS}-${ARCH}.tar.gz v8/build/linux/*-sysroot/*
      - name: Upload headers
        if: env.LIB_TYPE == 'static' && env.BUILD_TYPE == 'release'
        uses: actions/upload-artifact@v4
        with:
          path: v8-${{ env.V8_VERSION }}-include.tar.gz
          name: v8-${{ env.V8_VERSION }}-include.tar.gz
      - name: Upload sources
        if: env.LIB_TYPE == 'static' && env.BUILD_TYPE == 'release'
        uses: actions/upload-artifact@v4
        with:
          path: v8-${{ env.V8_VERSION }}-src.tar.gz
          name: v8-${{ env.V8_VERSION }}-src.tar.gz
      - name: Upload linux sysroot
        if: env.LIB_TYPE == 'static' && env.BUILD_TYPE == 'release'
        uses: actions/upload-artifact@v4
        with:
          path: v8-${{ env.V8_VERSION }}-sysroot-${{ env.OS }}-${{ env.ARCH }}.tar.gz
          name: v8-${{ env.V8_VERSION }}-sysroot-${{ env.OS }}-${{ env.ARCH }}.tar.gz
      - name: Set build args
        run: |
          cd v8
          mkdir -p out.gn/${PLATFORM}
          export IS_CLANG=false
          [ "$BUILD_TYPE" = "debug" ] && \
            export IS_DEBUG=true SYMBOL_LEVEL=2 || \
            export IS_DEBUG=false SYMBOL_LEVEL=1
          [ "$LIB_TYPE" = "shared" ] && \
            export SHARED_LIB=true STATIC_LIB=false || \
            export SHARED_LIB=false STATIC_LIB=true
          perl -pe 's{\$(\{)?(\w+)(?(1)\})}{$ENV{$2} // $&}ge' \
            "${GITHUB_WORKSPACE}/args.gn" > "out.gn/${PLATFORM}/args.gn"
          cat out.gn/${PLATFORM}/args.gn
      - name: Build library
        run: |
          cd v8
          gn gen out.gn/${PLATFORM}
          export BUILD_TARGETS=(v8 v8_base v8_libbase v8_libplatform icui18n icuuc)
          [ "$LIB_TYPE" = "static" ] && BUILD_TARGETS+=(v8_monolith); export BUILD_TARGETS
          ninja -j $(($(nproc)+2)) ${BUILD_TARGETS[@]} -C out.gn/${PLATFORM}
          gn args --list --short out.gn/${PLATFORM} > out.gn/${PLATFORM}/gn_args_list.txt
      - name: Compress library
        run: |
          tar -cf v8-${V8_VERSION}-lib-${PLATFORM}.tar \
            --transform="s|^v8/out.gn/${PLATFORM}/|v8/|" v8/out.gn/${PLATFORM}/gn_args_list.txt
          find v8/out.gn/${PLATFORM} -name "*.a" -o -name "*.so" | tar -rf v8-${V8_VERSION}-lib-${PLATFORM}.tar \
            --transform="s|^v8/out.gn.*/|v8/lib/|" -T -
          gzip v8-${V8_VERSION}-lib-${PLATFORM}.tar
      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          path: v8-${{ env.V8_VERSION }}-lib-${{ matrix.platform }}.tar.gz
          name: v8-${{ env.V8_VERSION }}-lib-${{ matrix.platform }}.tar.gz

  build-linux-arm64:
    # if: ${{ false }}  # disable
    name: linux-arm64
    runs-on: ubuntu-22.04-arm
    container:
      image: debian:buster
    strategy:
      fail-fast: false
      matrix:
        platform: [
          linux-arm64-static-release,
          linux-arm64-static-debug,
          linux-arm64-shared-release,
          linux-arm64-shared-debug
        ]
    env:
      PLATFORM: ${{ matrix.platform }}
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Platform env
        run: |
          uname -a
          echo "OS=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $1}')" >> $GITHUB_ENV
          echo "ARCH=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $2}')" >> $GITHUB_ENV
          echo "LIB_TYPE=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $3}')" >> $GITHUB_ENV
          echo "BUILD_TYPE=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $4}')" >> $GITHUB_ENV
      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y git python3 curl build-essential pkg-config ninja-build
          ln -s /usr/bin/python3 /usr/bin/python
          gcc --version
          ldd --version
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "PATH=${GITHUB_WORKSPACE}/depot_tools:${PATH}" >> $GITHUB_ENV
      - name: Patch depot_tools for python3.7
        run: |
          sed -i 's/@functools\.lru_cache\b/@functools.lru_cache(maxsize=128)/g' depot_tools/gclient_paths.py
      - name: Fetch v8 repository
        run: |
          gclient --version
          fetch v8
      - name: Sync v8 repository to target version
        run: |
          cd v8
          git checkout tags/${V8_VERSION}
          gclient sync -D
      - name: Compress headers, sources, sysroot
        if: env.LIB_TYPE == 'static' && env.BUILD_TYPE == 'release'
        run: |
          tar -czf v8-${V8_VERSION}-sysroot-${OS}-${ARCH}.tar.gz v8/build/linux/*-sysroot/*
      - name: Upload linux sysroot
        if: env.LIB_TYPE == 'static' && env.BUILD_TYPE == 'release'
        uses: actions/upload-artifact@v4
        with:
          path: v8-${{ env.V8_VERSION }}-sysroot-${{ env.OS }}-${{ env.ARCH }}.tar.gz
          name: v8-${{ env.V8_VERSION }}-sysroot-${{ env.OS }}-${{ env.ARCH }}.tar.gz
      - name: Patch gn for arm64
        run: |
          cd v8
          mv buildtools/linux64/gn buildtools/linux64/gn-x64
          curl -L https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-arm64/+/latest -o gn-linux-arm64.zip
          apt-get install -y unzip
          unzip gn-linux-arm64.zip -d buildtools/linux64
          sed -i 's/visibility = \[ ":.*" \]\([[:space:]]*#.*\)\?/visibility = [ ":*", "\/\/testing\/gmock:*" ]\1/' third_party/googletest/BUILD.gn
      - name: Set build args
        run: |
          cd v8
          mkdir -p out.gn/${PLATFORM}
          export IS_CLANG=false
          [ "$BUILD_TYPE" = "debug" ] && \
            export IS_DEBUG=true SYMBOL_LEVEL=2 || \
            export IS_DEBUG=false SYMBOL_LEVEL=1
          [ "$LIB_TYPE" = "shared" ] && \
            export SHARED_LIB=true STATIC_LIB=false || \
            export SHARED_LIB=false STATIC_LIB=true
          perl -pe 's{\$(\{)?(\w+)(?(1)\})}{$ENV{$2} // $&}ge' \
            "${GITHUB_WORKSPACE}/args.gn" > "out.gn/${PLATFORM}/args.gn"
          cat out.gn/${PLATFORM}/args.gn
      - name: Build library
        run: |
          cd v8
          gn gen out.gn/${PLATFORM}
          export BUILD_TARGETS=(v8 v8_base v8_libbase v8_libplatform icui18n icuuc)
          [ "$LIB_TYPE" = "static" ] && BUILD_TARGETS+=(v8_monolith); export BUILD_TARGETS
          ninja -j $(($(nproc)+2)) ${BUILD_TARGETS[@]} -C out.gn/${PLATFORM}
          gn args --list --short out.gn/${PLATFORM} > out.gn/${PLATFORM}/gn_args_list.txt
      - name: Compress library
        run: |
          tar -cf v8-${V8_VERSION}-lib-${PLATFORM}.tar \
            --transform="s|^v8/out.gn/${PLATFORM}/|v8/|" v8/out.gn/${PLATFORM}/gn_args_list.txt
          find v8/out.gn/${PLATFORM} -name "*.a" -o -name "*.so" | tar -rf v8-${V8_VERSION}-lib-${PLATFORM}.tar \
            --transform="s|^v8/out.gn.*/|v8/lib/|" -T -
          gzip v8-${V8_VERSION}-lib-${PLATFORM}.tar
      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          path: v8-${{ env.V8_VERSION }}-lib-${{ matrix.platform }}.tar.gz
          name: v8-${{ env.V8_VERSION }}-lib-${{ matrix.platform }}.tar.gz

  build-mac-x64:
    # if: ${{ false }}  # disable
    name: mac-x64
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        platform: [
          mac-x64-static-release,
          mac-x64-static-debug,
          mac-x64-shared-release,
          mac-x64-shared-debug
        ]
    env:
      PLATFORM: ${{ matrix.platform }}
    steps:
      - name: Platform env
        run: |
          uname -a
          echo "OS=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $1}')" >> $GITHUB_ENV
          echo "ARCH=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $2}')" >> $GITHUB_ENV
          echo "LIB_TYPE=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $3}')" >> $GITHUB_ENV
          echo "BUILD_TYPE=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $4}')" >> $GITHUB_ENV
      - name: Setup Python3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "PATH=${GITHUB_WORKSPACE}/depot_tools:${PATH}" >> $GITHUB_ENV
      - name: Fetch v8 repository
        run: |
          gclient --version
          fetch v8
      - name: Sync v8 repository to target version
        run: |
          cd v8
          git checkout tags/${V8_VERSION}
          gclient sync -D
      # - name: Patch v8 for python3.13
      #   run: |
      #     cd v8
      #     sed -i '' 's/from collections import Mapping/from collections.abc import Mapping/' third_party/jinja2/tests.py
      - name: Set build args
        run: |
          cd v8
          mkdir -p out.gn/${PLATFORM}
          export IS_CLANG=true
          [ "$BUILD_TYPE" = "debug" ] && \
            export IS_DEBUG=true SYMBOL_LEVEL=2 || \
            export IS_DEBUG=false SYMBOL_LEVEL=1
          [ "$LIB_TYPE" = "shared" ] && \
            export SHARED_LIB=true STATIC_LIB=false || \
            export SHARED_LIB=false STATIC_LIB=true
          perl -pe 's{\$(\{)?(\w+)(?(1)\})}{$ENV{$2} // $&}ge' \
            "${GITHUB_WORKSPACE}/args.gn" > "out.gn/${PLATFORM}/args.gn"
          cat out.gn/${PLATFORM}/args.gn
      - name: Build library
        run: |
          cd v8
          gn gen out.gn/${PLATFORM}
          export BUILD_TARGETS=(v8 v8_base v8_libbase v8_libplatform icui18n icuuc)
          [ "$LIB_TYPE" = "static" ] && BUILD_TARGETS+=(v8_monolith); export BUILD_TARGETS
          ninja -j $(($(sysctl -n hw.ncpu)+2)) ${BUILD_TARGETS[@]} -C out.gn/${PLATFORM}
          gn args --list --short out.gn/${PLATFORM} > out.gn/${PLATFORM}/gn_args_list.txt
      - name: Compress library
        run: |
          gtar -cf v8-${V8_VERSION}-lib-${PLATFORM}.tar \
            --transform="s|^v8/out.gn/${PLATFORM}/|v8/|" v8/out.gn/${PLATFORM}/gn_args_list.txt
          find v8/out.gn/${PLATFORM} -name "*.a" -o -name "*.dylib" | gtar -rf v8-${V8_VERSION}-lib-${PLATFORM}.tar \
            --transform="s|^v8/out.gn.*/|v8/lib/|" -T -
          gzip v8-${V8_VERSION}-lib-${PLATFORM}.tar
      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          path: v8-${{ env.V8_VERSION }}-lib-${{ matrix.platform }}.tar.gz
          name: v8-${{ env.V8_VERSION }}-lib-${{ matrix.platform }}.tar.gz

  build-mac-arm64:
    # if: ${{ false }}  # disable
    name: mac-arm64
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [
          mac-arm64-static-release,
          mac-arm64-static-debug,
          mac-arm64-shared-release,
          mac-arm64-shared-debug
        ]
    env:
      PLATFORM: ${{ matrix.platform }}
    steps:
      - name: Platform env
        run: |
          uname -a
          echo "OS=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $1}')" >> $GITHUB_ENV
          echo "ARCH=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $2}')" >> $GITHUB_ENV
          echo "LIB_TYPE=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $3}')" >> $GITHUB_ENV
          echo "BUILD_TYPE=$(echo ${PLATFORM} | awk -F'[-_.]' '{print $4}')" >> $GITHUB_ENV
      - name: Setup Python3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "PATH=${GITHUB_WORKSPACE}/depot_tools:${PATH}" >> $GITHUB_ENV
      - name: Fetch v8 repository
        run: |
          gclient --version
          fetch v8
      - name: Sync v8 repository to target version
        run: |
          cd v8
          git checkout tags/${V8_VERSION}
          gclient sync -D
      # - name: Patch v8 for python3.13
      #   run: |
      #     cd v8
      #     sed -i '' 's/from collections import Mapping/from collections.abc import Mapping/' third_party/jinja2/tests.py
      - name: Set build args
        run: |
          cd v8
          mkdir -p out.gn/${PLATFORM}
          export IS_CLANG=true
          [ "$BUILD_TYPE" = "debug" ] && \
            export IS_DEBUG=true SYMBOL_LEVEL=2 || \
            export IS_DEBUG=false SYMBOL_LEVEL=1
          [ "$LIB_TYPE" = "shared" ] && \
            export SHARED_LIB=true STATIC_LIB=false || \
            export SHARED_LIB=false STATIC_LIB=true
          perl -pe 's{\$(\{)?(\w+)(?(1)\})}{$ENV{$2} // $&}ge' \
            "${GITHUB_WORKSPACE}/args.gn" > "out.gn/${PLATFORM}/args.gn"
          cat out.gn/${PLATFORM}/args.gn
      - name: Build library
        run: |
          cd v8
          gn gen out.gn/${PLATFORM}
          export BUILD_TARGETS=(v8 v8_base v8_libbase v8_libplatform icui18n icuuc)
          [ "$LIB_TYPE" = "static" ] && BUILD_TARGETS+=(v8_monolith); export BUILD_TARGETS
          ninja -j $(($(sysctl -n hw.ncpu)+2)) ${BUILD_TARGETS[@]} -C out.gn/${PLATFORM}
          gn args --list --short out.gn/${PLATFORM} > out.gn/${PLATFORM}/gn_args_list.txt
      - name: Compress library
        run: |
          gtar -cf v8-${V8_VERSION}-lib-${PLATFORM}.tar \
            --transform="s|^v8/out.gn/${PLATFORM}/|v8/|" v8/out.gn/${PLATFORM}/gn_args_list.txt
          find v8/out.gn/${PLATFORM} -name "*.a" -o -name "*.dylib" | gtar -rf v8-${V8_VERSION}-lib-${PLATFORM}.tar \
            --transform="s|^v8/out.gn.*/|v8/lib/|" -T -
          gzip v8-${V8_VERSION}-lib-${PLATFORM}.tar
      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          path: v8-${{ env.V8_VERSION }}-lib-${{ matrix.platform }}.tar.gz
          name: v8-${{ env.V8_VERSION }}-lib-${{ matrix.platform }}.tar.gz
